// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public  class Embed : Gtk.Widget {

		[Obsolete]
		protected Embed(GLib.GType gtype) : base(gtype) {}
		public Embed(IntPtr raw) : base(raw) {}

		[DllImport("clutter-gtk")]
		static extern IntPtr gtk_clutter_embed_new();

		public Embed () : base (IntPtr.Zero)
		{
			if (GetType () != typeof (Embed)) {
				CreateNativeObject (new string [0], new GLib.Value[0]);
				return;
			}
			Raw = gtk_clutter_embed_new();
		}

		[DllImport("clutter-gtk")]
		static extern IntPtr gtk_clutter_embed_get_stage(IntPtr raw);

		public Clutter.Actor Stage { 
			get {
				IntPtr raw_ret = gtk_clutter_embed_get_stage(Handle);
				Clutter.Actor ret = GLib.Object.GetObject(raw_ret) as Clutter.Actor;
				return ret;
			}
		}

		[DllImport("clutter-gtk")]
		static extern IntPtr gtk_clutter_embed_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = gtk_clutter_embed_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}


		static Embed ()
		{
			GtkSharp.ClutterSharp.ObjectManager.Initialize ();
		}
#endregion
	}
}
