// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void ActorRemovedHandler(object o, ActorRemovedArgs args);

	public class ActorRemovedArgs : GLib.SignalArgs {
		public Clutter.Actor Actor{
			get {
				return (Clutter.Actor) Args[0];
			}
		}

	}
}
