// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct AnyEvent {

		public Clutter.EventType Type;

		public static Clutter.AnyEvent Zero = new Clutter.AnyEvent ();

		public static Clutter.AnyEvent New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Clutter.AnyEvent.Zero;
			}
			Clutter.AnyEvent self = new Clutter.AnyEvent();
			self = (Clutter.AnyEvent) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		private static GLib.GType GType {
			get { return GLib.GType.Pointer; }
		}
#endregion
	}
}
