// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public  class BehaviourDepth : Clutter.Behaviour {

		[Obsolete]
		protected BehaviourDepth(GLib.GType gtype) : base(gtype) {}
		public BehaviourDepth(IntPtr raw) : base(raw) {}

		[DllImport("clutter")]
		static extern IntPtr clutter_behaviour_depth_new(IntPtr alpha, int depth_start, int depth_end);

		public BehaviourDepth (Clutter.Alpha alpha, int depth_start, int depth_end) : base (IntPtr.Zero)
		{
			if (GetType () != typeof (BehaviourDepth)) {
				ArrayList vals = new ArrayList();
				ArrayList names = new ArrayList();
				if (alpha != null) {
					names.Add ("alpha");
					vals.Add (new GLib.Value (alpha));
				}
				names.Add ("depth_start");
				vals.Add (new GLib.Value (depth_start));
				names.Add ("depth_end");
				vals.Add (new GLib.Value (depth_end));
				CreateNativeObject ((string[])names.ToArray (typeof (string)), (GLib.Value[])vals.ToArray (typeof (GLib.Value)));
				return;
			}
			Raw = clutter_behaviour_depth_new(alpha == null ? IntPtr.Zero : alpha.Handle, depth_start, depth_end);
		}

		[GLib.Property ("depth-end")]
		public int DepthEnd {
			get {
				GLib.Value val = GetProperty ("depth-end");
				int ret = (int) val;
				val.Dispose ();
				return ret;
			}
			set {
				GLib.Value val = new GLib.Value(value);
				SetProperty("depth-end", val);
				val.Dispose ();
			}
		}

		[GLib.Property ("depth-start")]
		public int DepthStart {
			get {
				GLib.Value val = GetProperty ("depth-start");
				int ret = (int) val;
				val.Dispose ();
				return ret;
			}
			set {
				GLib.Value val = new GLib.Value(value);
				SetProperty("depth-start", val);
				val.Dispose ();
			}
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_behaviour_depth_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = clutter_behaviour_depth_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("clutter")]
		static extern void clutter_behaviour_depth_set_bounds(IntPtr raw, int depth_start, int depth_end);

		public void SetBounds(int depth_start, int depth_end) {
			clutter_behaviour_depth_set_bounds(Handle, depth_start, depth_end);
		}

		[DllImport("clutter")]
		static extern void clutter_behaviour_depth_get_bounds(IntPtr raw, out int depth_start, out int depth_end);

		public void GetBounds(out int depth_start, out int depth_end) {
			clutter_behaviour_depth_get_bounds(Handle, out depth_start, out depth_end);
		}

#endregion
	}
}
