// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void ButtonPressEventHandler(object o, ButtonPressEventArgs args);

	public class ButtonPressEventArgs : GLib.SignalArgs {
		public Clutter.ButtonEvent Event{
			get {
				return (Clutter.ButtonEvent) Args[0];
			}
		}

	}
}
