// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void ChildNotifyHandler(object o, ChildNotifyArgs args);

	public class ChildNotifyArgs : GLib.SignalArgs {
		public Clutter.Actor Actor{
			get {
				return (Clutter.Actor) Args[0];
			}
		}

		public IntPtr Pspec{
			get {
				return (IntPtr) Args[1];
			}
		}

	}
}
