// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace ClutterSharp {

	using System;

#region Autogenerated code
	[GLib.CDeclCallback]
	internal delegate uint AlphaFuncNative(IntPtr alpha, IntPtr user_data);

	internal class AlphaFuncWrapper {

		public uint NativeCallback (IntPtr alpha, IntPtr user_data)
		{
			Clutter.Alpha _arg0 = GLib.Object.GetObject(alpha) as Clutter.Alpha;
			return (uint) (managed ( _arg0));
		}

		internal AlphaFuncNative NativeDelegate;
		Clutter.AlphaFunc managed;

		public AlphaFuncWrapper (Clutter.AlphaFunc managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new AlphaFuncNative (NativeCallback);
		}

		public static Clutter.AlphaFunc GetManagedDelegate (AlphaFuncNative native)
		{
			if (native == null)
				return null;
			AlphaFuncWrapper wrapper = (AlphaFuncWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
#endregion
}
