// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace ClutterSharp {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.CDeclCallback]
	internal delegate bool ModelFilterFuncNative(IntPtr model, IntPtr iter, IntPtr user_data);

	internal class ModelFilterFuncWrapper {

		public bool NativeCallback (IntPtr model, IntPtr iter, IntPtr user_data)
		{
			try {
				Clutter.Model _arg0 = GLib.Object.GetObject(model) as Clutter.Model;
				Clutter.ModelIter _arg1 = GLib.Object.GetObject(iter) as Clutter.ModelIter;
				bool ret = (bool) (managed ( _arg0,  _arg1));
				if (release_on_call)
					gch.Free ();
				return ret;
			} catch (Exception e) {
				GLib.ExceptionManager.RaiseUnhandledException (e, false);
				return false;
			}
		}

		bool release_on_call = false;
		GCHandle gch;

		public void PersistUntilCalled ()
		{
			release_on_call = true;
			gch = GCHandle.Alloc (this);
		}

		internal ModelFilterFuncNative NativeDelegate;
		Clutter.ModelFilterFunc managed;

		public ModelFilterFuncWrapper (Clutter.ModelFilterFunc managed)
		{
			this.managed = managed;
			if (managed != null)
				NativeDelegate = new ModelFilterFuncNative (NativeCallback);
		}

		public static Clutter.ModelFilterFunc GetManagedDelegate (ModelFilterFuncNative native)
		{
			if (native == null)
				return null;
			ModelFilterFuncWrapper wrapper = (ModelFilterFuncWrapper) native.Target;
			if (wrapper == null)
				return null;
			return wrapper.managed;
		}
	}
#endregion
}
