// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

#region Autogenerated code
	public interface Container : GLib.IWrapper {

		event Clutter.ActorRemovedHandler ActorRemoved;
		event Clutter.ActorAddedHandler ActorAdded;
		void AddValist(Clutter.Actor first_actor, IntPtr var_args);
		void AddActor(Clutter.Actor actor);
		void SortDepthOrder();
		void LowerChild(Clutter.Actor actor, Clutter.Actor sibling);
		void RaiseChild(Clutter.Actor actor, Clutter.Actor sibling);
		void RemoveValist(Clutter.Actor first_actor, IntPtr var_args);
		Clutter.Actor FindChildByName(string child_name);
		void RemoveActor(Clutter.Actor actor);
		void Foreach(Clutter.Callback cb);
		GLib.List Children { 
			get;
		}
	}
#endregion
}
