// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum DebugFlag {

		Misc = 1 << 0,
		Actor = 1 << 1,
		Texture = 1 << 2,
		Event = 1 << 3,
		Paint = 1 << 4,
		Gl = 1 << 5,
		Alpha = 1 << 6,
		Behaviour = 1 << 7,
		Pango = 1 << 8,
	}
#endregion
}
