// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void EnterEventHandler(object o, EnterEventArgs args);

	public class EnterEventArgs : GLib.SignalArgs {
		public Clutter.CrossingEvent Event{
			get {
				return (Clutter.CrossingEvent) Args[0];
			}
		}

	}
}
