// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void ErrorHandler(object o, ErrorArgs args);

	public class ErrorArgs : GLib.SignalArgs {
		public IntPtr Error{
			get {
				return (IntPtr) Args[0];
			}
		}

	}
}
