// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Event {

		[DllImport("clutter")]
		static extern IntPtr clutter_event_get_type();

		public static GLib.GType GType { 
			get {
				IntPtr raw_ret = clutter_event_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

#endregion
	}
}
