// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Exp {

		[DllImport("clutter")]
		static extern uint clutter_exp_dec_func(IntPtr alpha, IntPtr dummy);

		public static uint DecFunc(Clutter.Alpha alpha, IntPtr dummy) {
			uint raw_ret = clutter_exp_dec_func(alpha == null ? IntPtr.Zero : alpha.Handle, dummy);
			uint ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern uint clutter_exp_inc_func(IntPtr alpha, IntPtr dummy);

		public static uint IncFunc(Clutter.Alpha alpha, IntPtr dummy) {
			uint raw_ret = clutter_exp_inc_func(alpha == null ? IntPtr.Zero : alpha.Handle, dummy);
			uint ret = raw_ret;
			return ret;
		}

#endregion
	}
}
