// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Feature {

		[DllImport("clutter")]
		static extern bool clutter_feature_available(int feature);

		public static bool Available(Clutter.FeatureFlags feature) {
			bool raw_ret = clutter_feature_available((int) feature);
			bool ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern int clutter_feature_get_all();

		public static Clutter.FeatureFlags All { 
			get {
				int raw_ret = clutter_feature_get_all();
				Clutter.FeatureFlags ret = (Clutter.FeatureFlags) raw_ret;
				return ret;
			}
		}

#endregion
	}
}
