// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum FeatureFlags {

		TextureRectangle = 1 << 1,
		SyncToVblank = 1 << 2,
	}
#endregion
}
