// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct Geometry {

		public int X;
		public int Y;
		public uint Width;
		public uint Height;

		public static Clutter.Geometry Zero = new Clutter.Geometry ();

		public static Clutter.Geometry New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Clutter.Geometry.Zero;
			}
			Clutter.Geometry self = new Clutter.Geometry();
			self = (Clutter.Geometry) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_geometry_get_type();

		public static GLib.GType GType { 
			get {
				IntPtr raw_ret = clutter_geometry_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

#endregion
	}
}
