// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Global {

		[DllImport("clutter")]
		static extern bool clutter_want_debug();

		public static bool WantDebug() {
			bool raw_ret = clutter_want_debug();
			bool ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern uint clutter_keysym_to_unicode(uint keyval);

		public static uint KeysymToUnicode(uint keyval) {
			uint raw_ret = clutter_keysym_to_unicode(keyval);
			uint ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern uint clutter_sine_func(IntPtr alpha, IntPtr dummy);

		public static uint SineFunc(Clutter.Alpha alpha, IntPtr dummy) {
			uint raw_ret = clutter_sine_func(alpha == null ? IntPtr.Zero : alpha.Handle, dummy);
			uint ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern uint clutter_square_func(IntPtr alpha, IntPtr dummy);

		public static uint SquareFunc(Clutter.Alpha alpha, IntPtr dummy) {
			uint raw_ret = clutter_square_func(alpha == null ? IntPtr.Zero : alpha.Handle, dummy);
			uint ret = raw_ret;
			return ret;
		}

#endregion
	}
}
