// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.InitErrorGType))]
	public enum InitError {

		Success = 1,
		ErrorUnknown,
		ErrorThreads = -1,
		ErrorBackend = -2,
		ErrorInternal = -3,
	}

	internal class InitErrorGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_init_error_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_init_error_get_type ());
			}
		}
	}
#endregion
}
