// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Init {

		[DllImport("clutter")]
		static extern int clutter_init_error_quark();

		public static int ErrorQuark() {
			int raw_ret = clutter_init_error_quark();
			int ret = raw_ret;
			return ret;
		}

#endregion
	}
}
