// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class InputDevice : GLib.Opaque {

		public InputDevice(IntPtr raw) : base(raw) {}

#endregion
	}
}
