// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void KeyPressEventHandler(object o, KeyPressEventArgs args);

	public class KeyPressEventArgs : GLib.SignalArgs {
		public Clutter.KeyEvent Event{
			get {
				return (Clutter.KeyEvent) Args[0];
			}
		}

	}
}
