// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void KnotReachedHandler(object o, KnotReachedArgs args);

	public class KnotReachedArgs : GLib.SignalArgs {
		public Clutter.Knot Knot{
			get {
				return (Clutter.Knot) Args[0];
			}
		}

	}
}
