// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Main {

		[DllImport("clutter")]
		static extern void clutter_main_quit();

		public static void Quit() {
			clutter_main_quit();
		}

		[DllImport("clutter")]
		static extern int clutter_main_level();

		public static int Level() {
			int raw_ret = clutter_main_level();
			int ret = raw_ret;
			return ret;
		}

#endregion
	}
}
