// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void MarkerReachedHandler(object o, MarkerReachedArgs args);

	public class MarkerReachedArgs : GLib.SignalArgs {
		public string MarkerName{
			get {
				return (string) Args[0];
			}
		}

		public int FrameNum{
			get {
				return (int) Args[1];
			}
		}

	}
}
