// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate bool ModelFilterFunc(Clutter.Model model, Clutter.ModelIter iter);

}
