// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate int ModelSortFunc(Clutter.Model model, GLib.Value a, GLib.Value b);

}
