// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct MotionEvent {

		public Clutter.EventType Type;
		public uint Time;
		public int X;
		public int Y;
		public Clutter.ModifierType ModifierState;
		private IntPtr _axes;
		private IntPtr _device;
		public Clutter.InputDevice Device {
			get {
				return _device == IntPtr.Zero ? null : (Clutter.InputDevice) GLib.Opaque.GetOpaque (_device, typeof (Clutter.InputDevice), false);
			}
			set {
				_device = value == null ? IntPtr.Zero : value.Handle;
			}
		}

		public static Clutter.MotionEvent Zero = new Clutter.MotionEvent ();

		public static Clutter.MotionEvent New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Clutter.MotionEvent.Zero;
			}
			Clutter.MotionEvent self = new Clutter.MotionEvent();
			self = (Clutter.MotionEvent) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		private static GLib.GType GType {
			get { return GLib.GType.Pointer; }
		}
#endregion
	}
}
