// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.PackTypeGType))]
	public enum PackType {

		Start,
		End,
	}

	internal class PackTypeGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_pack_type_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_pack_type_get_type ());
			}
		}
	}
#endregion
}
