// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct Padding {

		public int Top;
		public int Right;
		public int Bottom;
		public int Left;

		public static Clutter.Padding Zero = new Clutter.Padding ();

		public static Clutter.Padding New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Clutter.Padding.Zero;
			}
			Clutter.Padding self = new Clutter.Padding();
			self = (Clutter.Padding) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_padding_get_type();

		public static GLib.GType GType { 
			get {
				IntPtr raw_ret = clutter_padding_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("glibsharpglue-2")]
		static extern IntPtr glibsharp_value_get_boxed (ref GLib.Value val);

		[DllImport("glibsharpglue-2")]
		static extern void glibsharp_value_set_boxed (ref GLib.Value val, ref Clutter.Padding boxed);

		public static explicit operator GLib.Value (Clutter.Padding boxed)
		{
			GLib.Value val = GLib.Value.Empty;
			val.Init (Clutter.Padding.GType);
			glibsharp_value_set_boxed (ref val, ref boxed);
			return val;
		}

		public static explicit operator Clutter.Padding (GLib.Value val)
		{
			IntPtr boxed_ptr = glibsharp_value_get_boxed (ref val);
			return New (boxed_ptr);
		}
#endregion
	}
}
