// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void ParentSetHandler(object o, ParentSetArgs args);

	public class ParentSetArgs : GLib.SignalArgs {
		public Clutter.Actor OldParent{
			get {
				return (Clutter.Actor) Args[0];
			}
		}

	}
}
