// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.RotateAxisGType))]
	public enum RotateAxis {

		XAxis,
		YAxis,
		ZAxis,
	}

	internal class RotateAxisGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_rotate_axis_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_rotate_axis_get_type ());
			}
		}
	}
#endregion
}
