// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void RowAddedHandler(object o, RowAddedArgs args);

	public class RowAddedArgs : GLib.SignalArgs {
		public Clutter.ModelIter Iter{
			get {
				return (Clutter.ModelIter) Args[0];
			}
		}

	}
}
