// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void RowChangedHandler(object o, RowChangedArgs args);

	public class RowChangedArgs : GLib.SignalArgs {
		public Clutter.ModelIter Iter{
			get {
				return (Clutter.ModelIter) Args[0];
			}
		}

	}
}
