// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void RowRemovedHandler(object o, RowRemovedArgs args);

	public class RowRemovedArgs : GLib.SignalArgs {
		public Clutter.ModelIter Iter{
			get {
				return (Clutter.ModelIter) Args[0];
			}
		}

	}
}
