// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

#region Autogenerated code
	public interface Scriptable : GLib.IWrapper {

		void SetCustomProperty(Clutter.Script script, string name, GLib.Value value);
		string Id { 
			get; set;
		}
	}
#endregion
}
