// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.ScriptErrorGType))]
	public enum ScriptError {

		TypeFunction,
		Property,
		Value,
	}

	internal class ScriptErrorGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_script_error_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_script_error_get_type ());
			}
		}
	}
#endregion
}
