// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.ScrollDirectionGType))]
	public enum ScrollDirection {

		Up,
		Down,
		Left,
		Right,
	}

	internal class ScrollDirectionGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_scroll_direction_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_scroll_direction_get_type ());
			}
		}
	}
#endregion
}
