// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[GLib.GType (typeof (Clutter.ShaderErrorGType))]
	public enum ShaderError {

		NoAsm,
		NoGlsl,
		Compile,
	}

	internal class ShaderErrorGType {
		[DllImport ("clutter")]
		static extern IntPtr clutter_shader_error_get_type ();

		public static GLib.GType GType {
			get {
				return new GLib.GType (clutter_shader_error_get_type ());
			}
		}
	}
#endregion
}
