// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void SizeChangeHandler(object o, SizeChangeArgs args);

	public class SizeChangeArgs : GLib.SignalArgs {
		public int Width{
			get {
				return (int) Args[0];
			}
		}

		public int Height{
			get {
				return (int) Args[1];
			}
		}

	}
}
