// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

#region Autogenerated code
	public interface StageWindow : GLib.IWrapper {

	}

	[GLib.GInterface (typeof (StageWindowAdapter))]
	public interface StageWindowImplementor : GLib.IWrapper {

		Clutter.Actor Wrapper { get; }
		string Title { set; }
		bool Fullscreen { set; }
		bool CursorVisible { set; }
		bool UserResizable { set; }
	}
#endregion
}
