// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[StructLayout(LayoutKind.Sequential)]
	public struct StageStateEvent {

		public Clutter.EventType Type;
		public Clutter.StageState ChangedMask;
		public Clutter.StageState NewState;

		public static Clutter.StageStateEvent Zero = new Clutter.StageStateEvent ();

		public static Clutter.StageStateEvent New(IntPtr raw) {
			if (raw == IntPtr.Zero) {
				return Clutter.StageStateEvent.Zero;
			}
			Clutter.StageStateEvent self = new Clutter.StageStateEvent();
			self = (Clutter.StageStateEvent) Marshal.PtrToStructure (raw, self.GetType ());
			return self;
		}

		private static GLib.GType GType {
			get { return GLib.GType.Pointer; }
		}
#endregion
	}
}
