// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public  class Stage : Clutter.Group {

		~Stage()
		{
			Dispose();
		}

		[Obsolete]
		protected Stage(GLib.GType gtype) : base(gtype) {}
		public Stage(IntPtr raw) : base(raw) {}

		protected Stage() : base(IntPtr.Zero)
		{
			CreateNativeObject (new string [0], new GLib.Value [0]);
		}

		[DllImport("clutter")]
		static extern void clutter_stage_set_color(IntPtr raw, ref Clutter.Color color);

		public void SetColor(Clutter.Color color) {
			clutter_stage_set_color(Handle, ref color);
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_stage_get_default();

		public static Clutter.Stage Default { 
			get {
				IntPtr raw_ret = clutter_stage_get_default();
				Clutter.Stage ret = GLib.Object.GetObject(raw_ret) as Clutter.Stage;
				return ret;
			}
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_stage_snapshot(IntPtr raw, int x, int y, int width, int height);

		public Gdk.Pixbuf Snapshot(int x, int y, int width, int height) {
			IntPtr raw_ret = clutter_stage_snapshot(Handle, x, y, width, height);
			Gdk.Pixbuf ret = GLib.Object.GetObject(raw_ret) as Gdk.Pixbuf;
			return ret;
		}

		[DllImport("clutter")]
		static extern void clutter_stage_get_color(IntPtr raw, ref Clutter.Color color);

		public void GetColor(Clutter.Color color) {
			clutter_stage_get_color(Handle, ref color);
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_stage_get_type();

		public static new GLib.GType GType { 
			get {
				IntPtr raw_ret = clutter_stage_get_type();
				GLib.GType ret = new GLib.GType(raw_ret);
				return ret;
			}
		}

		[DllImport("clutter")]
		static extern IntPtr clutter_stage_get_actor_at_pos(IntPtr raw, int x, int y);

		public Clutter.Actor GetActorAtPos(int x, int y) {
			IntPtr raw_ret = clutter_stage_get_actor_at_pos(Handle, x, y);
			Clutter.Actor ret = GLib.Object.GetObject(raw_ret) as Clutter.Actor;
			return ret;
		}

#endregion
	}
}
