// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;

	public delegate void TimelineStartedHandler(object o, TimelineStartedArgs args);

	public class TimelineStartedArgs : GLib.SignalArgs {
		public Clutter.Timeline Timeline{
			get {
				return (Clutter.Timeline) Args[0];
			}
		}

	}
}
