// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Ungrab {

		[DllImport("clutter")]
		static extern void clutter_ungrab_pointer_for_device(int id);

		public static void PointerForDevice(int id) {
			clutter_ungrab_pointer_for_device(id);
		}

		[DllImport("clutter")]
		static extern void clutter_ungrab_pointer();

		public static void Pointer() {
			clutter_ungrab_pointer();
		}

		[DllImport("clutter")]
		static extern void clutter_ungrab_keyboard();

		public static void Keyboard() {
			clutter_ungrab_keyboard();
		}

#endregion
	}
}
