// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Clutter {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Util {

		[DllImport("clutter")]
		static extern int clutter_util_untrap_x_errors();

		public static int UntrapXErrors() {
			int raw_ret = clutter_util_untrap_x_errors();
			int ret = raw_ret;
			return ret;
		}

		[DllImport("clutter")]
		static extern void clutter_util_trap_x_errors();

		public static void TrapXErrors() {
			clutter_util_trap_x_errors();
		}

		[DllImport("clutter")]
		static extern int clutter_util_next_p2(int a);

		public static int NextP2(int a) {
			int raw_ret = clutter_util_next_p2(a);
			int ret = raw_ret;
			return ret;
		}

#endregion
	}
}
